Models/AddTodoViewModel.cs
namespace FinalTodoApp.Models
{
    public class AddTodoViewModel
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime Due { get; set; }
    }
}

Models/Domain/Todo.cs
namespace FinalTodoApp.Models.Domain
{
    public class Todo
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime Due { get; set; }
        public bool isCompleted { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace FinalTodoApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/UpdateTodoViewModel.cs
namespace FinalTodoApp.Models
{
    public class UpdateTodoViewModel
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime Due { get; set; }
        public bool isCompleted { get; set; }
    }
}

Models/VMLogin.cs
namespace FinalTodoApp.Models
{
    public class VMLogin
    {

        public string Email { get; set; }
        public string Password { get; set; }
        public bool KeepLoggedIn { get; set; }
    }
}

Controllers/AccessController.cs
using FinalTodoApp.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;


namespace FinalTodoApp.Controllers
{
    public class AccessController : Controller
    {
        public IActionResult Login()
        {
            ClaimsPrincipal claimUser = HttpContext.User;
            if (claimUser.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(VMLogin modelLogin)
        {

            if (modelLogin.Email == "admin@admin.com" && modelLogin.Password == "admin")
            {

                List<Claim> claims = new List<Claim>()
                {
                    new Claim(ClaimTypes.NameIdentifier,modelLogin.Email),
                    new Claim ("OtherProperties","Example Role")
                };

                ClaimsIdentity identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                AuthenticationProperties properties = new AuthenticationProperties()
                {
                    AllowRefresh = true,
                    IsPersistent = modelLogin.KeepLoggedIn,
                };
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity), properties);
                return RedirectToAction("Index", "Home");
            }
            ViewData["ValidateMessage"] = "User Not Found";
            return View();
        }

    }
}

Controllers/HomeController.cs
using FinalTodoApp.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FinalTodoApp.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login", "Access");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TodosController.cs
using FinalTodoApp.Data;
using FinalTodoApp.Models;
using FinalTodoApp.Models.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FinalTodoApp.Controllers
{
    [Authorize]
    public class TodosController : Controller
    {
        private readonly MVCDbContext mvcc;

        public TodosController(MVCDbContext mvcc)
        {
            this.mvcc = mvcc;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var todos = await mvcc.Todos.ToListAsync();
            return View(todos);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddTodoViewModel AddTodoRequest)
        {

            var todo = new Todo()
            {
                Id = Guid.NewGuid(),
                Title = AddTodoRequest.Title,
                Description = AddTodoRequest.Description,
                Due = AddTodoRequest.Due.ToUniversalTime(),
                isCompleted = false
            };
            await mvcc.Todos.AddAsync(todo);
            await mvcc.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var todo = await mvcc.Todos.FirstOrDefaultAsync(x => x.Id == id);

            if (todo != null)
            {
                var viewModel = new UpdateTodoViewModel()
                {
                    Id = todo.Id,
                    Title = todo.Title,
                    Description = todo.Description,
                    Due = todo.Due.ToUniversalTime(),
                    isCompleted = todo.isCompleted,
                };
                return await Task.Run(() => View("View", viewModel));
            }
            return RedirectToAction("Index");

        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateTodoViewModel model)
        {
            var todo = await mvcc.Todos.FindAsync(model.Id);
            if (todo != null)
            {
                todo.Title = model.Title;
                todo.Description = model.Description;
                todo.Due = model.Due.ToUniversalTime();
                todo.isCompleted = model.isCompleted;
                await mvcc.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateTodoViewModel model)
        {
            var todo = await mvcc.Todos.FindAsync(model.Id);
            if (todo != null)
            {
                mvcc.Todos.Remove(todo);
                await mvcc.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

    }
}

Views/Access/Login.cshtml
@model FinalTodoApp.Models.VMLogin;
@{
}

<form asp-controller="Access" asp-action="Login">
    <div class="mb-3">
        <label for="userEmail" class="form-label">Email address</label>
        <input type="email" asp-for="Email" class="form-control" id="userEmail">
    </div>
    <div class="mb-3">
        <label for="userPassword" class="form-label">Password</label>
        <input type="password" class="form-control" id="userPassword" asp-for="Password">
    </div>
    <div class="mb-3 form-check">
        <input asp-for="KeepLoggedIn" type="checkbox" class="form-check-input" id="keepMeLoggedin">
        <label class="form-check-label" for="keepMeLoggedin">Check me out</label>
    </div>
    <button type="submit" class="btn btn-primary">Login</button>

    @if(ViewData["ValidateMessage"]!=null)
    {
        <label>@ViewData["ValidateMessage"]</label>
    }

</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinalTodoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinalTodoApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinalTodoApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="todos" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LogOut">Log Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FinalTodoApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
</body>
</html>

Views/Todos/Add.cshtml
@model FinalTodoApp.Models.AddTodoViewModel
@{
}

<form action="Add" method="post">

    <div class="mb-3">
        <label for="taskTitle" class="form-label">Todo Title</label>
        <input type="text" class="form-control" id="taskTitle" asp-for="Title">
    </div>
    <div class="mb-3">
        <label for="taskDescription" class="form-label">Todo Description</label>
        <textarea class="form-control" id="taskDescription" rows="3" asp-for="Description"></textarea>
    </div>
    <div class="mb-3">
        <label for="taskDue" class="form-label">Due Date</label>
        <input type="date" class="form-control" asp-for="Due" id="taskDue">
    </div>
    <input type="submit" class="btn btn-primary" value="Add Todo">

</form>

Views/Todos/Index.cshtml
@model List<FinalTodoApp.Models.Domain.Todo>
@{
}
<a class="btn btn-primary" href="/todos/add"><i class="fa-solid fa-plus"></i> Add Task</a>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Due</th>
            <th scope="col">Status</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var todo in Model)
        {
        <tr>
            <td>@todo.Id</td>
            <td>@todo.Title</td>
            <td>@todo.Description</td>
            <td>@todo.Due</td>
            <td>@todo.isCompleted</td>
            <td>
                    <a class="btn btn-warning" href="/todos/View/@todo.Id"><i class="fa-solid fa-pencil"></i></a>
            </td>
        </tr>
        }
    </tbody>
</table>

Views/Todos/View.cshtml
@model FinalTodoApp.Models.UpdateTodoViewModel
@{
}

<form action="View" method="post">

    <div class="mb-3">
        <label for="taskTitle" class="form-label">Todo Title</label>
        <input type="text" class="form-control" id="taskTitle" asp-for="Id" readonly>
    </div>

    <div class="mb-3">
        <label for="taskTitle" class="form-label">Todo Title</label>
        <input type="text" class="form-control" id="taskTitle" asp-for="Title">
    </div>
    <div class="mb-3">
        <label for="taskDescription" class="form-label">Todo Description</label>
        <textarea class="form-control" id="taskDescription" rows="3" asp-for="Description"></textarea>
    </div>
    <div class="mb-3">
        <label for="taskDue" class="form-label">Due Date</label>
        <input type="date" class="form-control" asp-for="Due" id="taskDue">
    </div>
    <div class="mb-3">
        <input type="checkbox" id="TaskDone" value="true" asp-for="isCompleted">
        <label for="TaskDone">Is Completed</label>
    </div>

    <input type="submit" class="btn btn-primary" value="Add Todo">
    <input type="submit" class="btn btn-danger" asp-action="Delete" asp:asp-controller="Todos" value="Delete Todo">

</form>